type Gender = "male" | "female";

export const getRandomLastName = (): string => {
  return lastNames[Math.floor(Math.random() * lastNames.length)];
};

export const generateRandomName = (gender?: Gender): string => {
  if (!gender) {
    gender = Math.random() > 0.5 ? "male" : "female";
  }

  /** 1-2 first names concatinated by - */
  const firstName = [getRandomFirstName(gender)];
  if (Math.random() > 0.75) {
    firstName.push(getRandomFirstName(gender));
  }

  /** 1-2 last names concatinated by - */
  const lastName = [getRandomLastName()];
  if (Math.random() > 0.75) {
    lastName.push(getRandomLastName());
  }

  return `${firstName.join("-")} ${lastName.join("-")}`;
};

export const generateRandomNameWithTitle = (gender?: Gender): string => {
  if (!gender) {
    gender = Math.random() > 0.5 ? "male" : "female";
  }
  const name = generateRandomName(gender);
  const title = getRandomTitle(gender);
  const middleName = getRandomMiddleName();

  return `${name}, ${middleName} ${title}`;
};

export const getRandomMiddleName = (): string => {
  return middleNames[Math.floor(Math.random() * middleNames.length)];
};

export const getRandomFirstName = (gender: Gender): string => {
  const validFirstNames = gender === "male" ? maleFirstNames : femaleFirstNames;
  return validFirstNames[Math.floor(Math.random() * validFirstNames.length)];
};

export const getRandomTitle = (gender: Gender): string => {
  const validTitles = (gender === "male" ? maleTitles : femaleTitles).concat(
    neutralTitles
  );
  return validTitles[Math.floor(Math.random() * validTitles.length)];
};

const maleTitles = [
  "Mr.",
  "Master",
  "Sir",
  "Lord",
  "Duke",
  "Archduke",
  "King",
  "Prince",
  "Emperor",
  "High King",
  "High Prince",
  "High Emperor",
  "Lord Commander",
  "Lord Captain",
  "Lord Admiral",
  "Lord General",
  "Lord Marshal",
  "High Lord",
  "High Master",
  "High Sir",
  "High Duke",
  "Actor",
  "Witch King",
  "Witch Prince",
  "Witch Emperor",
];

const femaleTitles = [
  "Mrs.",
  "Ms.",
  "Miss",
  "Mistress",
  "Madam",
  "Lady",
  "Dame",
  "Countess",
  "Queen",
  "Princess",
  "Duchess",
  "Archduchess",
  "Empress",
  "High Queen",
  "High Princess",
  "High Duchess",
  "High Archduchess",
  "High Empress",
  "Hag",
  "Witch",
  "Actress",
  "High Lady",
  "High Mistress",
  "High Madam",
  "Witch Queen",
  "Witch Princess",
  "Witch Duchess",
];

const neutralTitles = [
  "Knight",
  "Wizard",
  "Rogue",
  "Cleric",
  "Bard",
  "Paladin",
  "Sorcerer",
  "Druid",
  "Warlock",
  "Barbarian",
  "Ranger",
  "Monk",
  "Fighter",
  "Baker",
  "Beggar",
  "Blacksmith",
  "Butcher",
  "Carpenter",
  "Cobbler",
  "Cook",
  "Farmer",
  "Fisherman",
  "Gardener",
  "Hunter",
  "Mason",
  "Miller",
  "Miner",
  "Potter",
  "Shepherd",
  "Tailor",
  "Weaver",
  "Woodcutter",
  "Brewer",
  "Merchant",
  "Sailor",
  "Shipwright",
  "Soldier",
  "Bishop",
  "Cardinal",
  "Deacon",
  "Friar",
  "Inquisitor",
  "Inspector",
  "Judge",
  "Lawyer",
  "Mayor",
  "Priest",
  "Professor",
  "Scribe",
  "Teacher",
  "Writer",
  "Artist",
  "Gambler",
  "Gravedigger",
  "Jester",
  "Gravekeeper",
  "Tanner",
  "Thief",
  "Burglar",
  "Assassin",
  "Spy",
  "Dancer",
  "Entertainer",
  "Juggler",
  "Minstrel",
  "Musician",
  "Poet",
  "Singer",
  "Actor",
  "Actress",
  "Comedian",
  "Commoner",
  "Haggler",
  "Hobo",
  "Peasant",
  "Servant",
  "Vagrant",
  "Villager",
  "Wanderer",
  "Witch Doctor",
  "Witch Hunter",
  "Witchfinder",
  "Witch Slayer",
  "Sheep herder",
  "Sheep farmer",
  "Sheep rancher",
  "Sheep breeder",
  "Sheep tender",
  "Librarian",
  "Archivist",
  "Bookkeeper",
  "Bookbinder",
  "Book Collector",
  "Book Dealer",
  "Book Historian",
  "Book Publisher",
  "Book Reviewer",
  "Fruit Grower",
  "Fruit Picker",
  "Fruit Packer",
  "Fruit Seller",
  "Fruit Buyer",
  "Cow Herder",
  "Cow Farmer",
  "Cow Rancher",
  "Cow Breeder",
  "Cow Tender",
  "Lover",
  "Friend",
];

const maleFirstNames = [
  "Gandalf",
  "Aragorn",
  "Legolas",
  "Frodo",
  "Gimli",
  "Bilbo",
  "Thorin",
  "Elrond",
  "Gollum",
  "Sauron",
  "Harry",
  "Ron",
  "Dumbledore",
  "Snape",
  "Voldemort",
  "Sirius",
  "Hagrid",
  "Neville",
  "Draco",
  "Dobby",
  "Dudley",
  "Luke",
  "Han",
  "Obi-Wan",
  "Anakin",
  "Yoda",
  "Mace",
  "Qui-Gon",
  "Chewbacca",
  "Darth",
  "Jabba",
  "Boba",
  "Jango",
  "Lando",
  "Wedge",
  "Poe",
  "Finn",
  "John",
  "Paul",
  "George",
  "Ringo",
  "Mick",
  "Keith",
  "Charlie",
  "Ronnie",
  "Brian",
  "Roger",
  "Pete",
  "James",
  "Lars",
  "Kirk",
  "Robert",
  "Dave",
  "Chris",
  "Kurt",
  "Krist",
  "Eddie",
  "Stone",
  "Jeff",
  "Mike",
  "Matt",
  "Taylor",
  "Nate",
  "Pat",
  "Mitch",
  "Lenny",
  "Benny",
  "Johnny",
  "Tommy",
  "Jimmy",
  "Jimbo",
  "Timmy",
  "Elroy",
  "Roy",
  "Ray",
  "Jay",
  "Jayson",
  "Jason",
  "Jaxon",
  "Montgomery",
  "Monty",
  "Mont",
  "Monte",
  "Montie",
  "Karl",
  "Carl",
  "Karlos",
  "Carlos",
  "Nedd",
  "Anthony",
  "Tony",
  "Anton",
  "Antonio",
  "Antonius",
  "Chad",
  "Chadwick",
  "Chadley",
  "Chadwickson",
  "Hans",
  "Hansel",
  "Hansson",
  "Pierre",
  "Andre",
  "Jean",
  "Jacques",
  "Thierry",
  "Louis",
  "Philippe",
  "Francois",
];

const femaleFirstNames = [
  "Hermione",
  "Luna",
  "Bellatrix",
  "Leia",
  "Padme",
  "Brenda",
  "Sharon",
  "Diane",
  "Debra",
  "Tammy",
  "Cheryl",
  "Janet",
  "Barbara",
  "Betty",
  "Nancy",
  "Helen",
  "Sandra",
  "Carolyn",
  "Shirley",
  "Raven",
  "Day",
  "Sun",
  "Moon",
  "Sky",
  "Cait",
  "Cara",
  "Carys",
  "Celyn",
  "Ceridwen",
  "Cerys",
  "Cordelia",
  "Delyth",
  "Dilys",
  "Eira",
  "Eirian",
  "Eirlys",
  "Eleri",
  "Elin",
  "Enid",
  "Alice",
  "Emma",
  "Olivia",
  "Sophia",
  "Ava",
  "Isabella",
  "Mia",
  "Charlotte",
  "Amelia",
  "Harper",
  "Evelyn",
  "Abigail",
  "Emily",
  "Mila",
  "Ella",
  "Avery",
  "Sofia",
  "Camila",
  "Aria",
  "Scarlett",
  "Madison",
  "Grace",
  "Chloe",
  "Penelope",
  "Layla",
  "Riley",
  "Zoey",
  "Nora",
  "Lily",
  "Eleanor",
  "Hannah",
  "Lillian",
  "Addison",
  "Aubrey",
  "Ellie",
  "Stella",
  "Natalie",
  "Zoe",
  "Leah",
  "Hazel",
  "Violet",
  "Aurora",
  "Savannah",
  "Audrey",
  "Brooklyn",
  "Bella",
  "Claire",
  "Skylar",
  "Lucy",
  "Paisley",
  "Everly",
  "Anna",
  "Caroline",
  "Nova",
  "Genesis",
  "Emilia",
  "Kennedy",
  "Samantha",
  "Maya",
  "Willow",
  "Kinsley",
  "Naomi",
  "Aaliyah",
  "Elena",
  "Sarah",
  "Ariana",
  "Allison",
  "Gabriella",
  "Charlie",
  "Arianna",
  "Valentina",
  "Isla",
  "Amaya",
  "Michelle",
  "Rebecca",
  "Alice",
  "Zara",
  "Eva",
  "Kristine",
  "Kristina",
  "Ane",
  "Anne",
  "Anna",
  "Annie",
  "Åse",
  "Astrid",
  "Bente",
  "Berit",
  "Birgit",
  "Bjørg",
  "Britt",
  "Camilla",
  "Carina",
  "Caroline",
  "Cecilie",
];

const middleNames = [
  "the Brave",
  "the Wise",
  "the Swift",
  "the Fearless",
  "the Mighty",
  "the Cunning",
  "the Valiant",
  "the Noble",
  "the Fierce",
  "the Loyal",
  "the Bold",
  "the Strong",
  "the Quick",
  "the Agile",
  "the Silent",
  "the One",
  "the Great",
  "the Terrible",
  "the Magnificent",
  "the Unyielding",
  "the Unbroken",
  "the Unbowed",
  "the Unbent",
  "the Unburnt",
  "the Unscarred",
  "the Unchained",
  "the Unchallenged",
  "the Unconquered",
  "the Unfettered",
  "the Unforgiven",
  "the Unforgotten",
  "the Unforgiving",
  "the Unhinged",
  "the Unholy",
  "the Unhallowed",
  "the Unhindered",
  "the Lazy",
  "the Unmotivated",
  "the Uninspired",
  "the Unimpressed",
  "the Uninterested",
  "the Unimpressive",
  "the Unimportant",
  "the Uninformed",
  "the Enlightened",
  "the Enigmatic",
  "the Unpredictable",
  "the Unusual",
  "the Uncommon",
  "the Unconventional",
  "the Unorthodox",
  "the Last",
  "the First",
  "the Second",
  "the Third",
  "the Fourth",
  "the Fifth",
  "the Sixth",
  "the Seventh",
  "the Eighth",
  "the Ninth",
  "the Tenth",
  "the Eleventh",
  "the one and only",
  "the Severed",
  "the Broken",
  "the Legendary",
  "the Mythical",
  "the Unbelievable",
  "the Unthinkable",
  "the Unimaginable",
  "the Unbearable",
  "the Unbreakable",
  "the Unstoppable",
  "the Loveable",
  "the Unlovable",
  "the Unlikable",
  "the Likable",
  "the Kind",
  "the Pure",
  "the Fair",
  "the Just",
  "the Righteous",
  "the Wicked",
  "the Evil",
  "the Cruel",
  "the Merciful",
  "the Compassionate",
  "the Forgiving",
  "the Thoughtful",
  "the Considerate",
  "the Caring",
  "the Loving",
  "the Hateful",
  "the Spiteful",
  "the Vengeful",
  "the Thoughtless",
  "the Inconsiderate",
  "the Selfish",
  "the Selfless",
  "the Old",
  "the Young",
  "the Ancient",
  "the Elder",
  "the Senior",
  "the Junior",
  "the Child",
  "the Kid",
  "the Baby",
  "the Experienced",
  "the Inexperienced",
  "the Novice",
  "the Master",
  "the Apprentice",
];

const lastNames = [
  "Stormrider",
  "Shadowbane",
  "Dragonheart",
  "Silvermoon",
  "Ironfist",
  "Fireforge",
  "Stonehammer",
  "Bloodaxe",
  "Blackthorn",
  "Ravenwood",
  "Lakeshire",
  "Goldshire",
  "Stormwind",
  "Ironforge",
  "Morogh",
  "Elwynn",
  "Westfall",
  "Redridge",
  "Duskwood",
  "Stranglethorn",
  "Sorrows",
  "Deadwind Pass",
  "Baggins",
  "Took",
  "Brandybuck",
  "Gamgee",
  "Bolger",
  "Sackville-Baggins",
  "Skywalker",
  "Solo",
  "Kenobi",
  "Palpatine",
  "Windu",
  "Fett",
  "Calrissian",
  "Antilles",
  "Dameron",
  "Finn",
  "Organa",
  "Amidala",
  "Tano",
  "Binks",
  "Lennon",
  "McCartney",
  "Harrison",
  "Starr",
  "Jagger",
  "Richards",
  "Watts",
  "Jones",
  "Wood",
  "Townshend",
  "Entwistle",
  "Moon",
  "Grohl",
  "Novoselic",
  "Cobain",
  "Cornell",
  "Cameron",
  "Gossard",
  "Ament",
  "McCready",
  "Hawkins",
  "Smear",
  "Shiflett",
  "Mendel",
  "Taylor",
  "Smith",
  "Plant",
  "Page",
  "Bonham",
  "Ulrich",
  "Hammett",
  "Trujillo",
  "Mustaine",
  "Ellefson",
  "Menza",
  "Friedman",
  "Rock",
  "Water",
  "Fire",
  "Earth",
  "Wind",
  "Light",
  "Dark",
  "Night",
  "Day",
  "Sun",
  "Star",
  "Sky",
  "Rain",
  "Snow",
  "Ice",
  "Frost",
  "Thunder",
  "Lightning",
  "Cloud",
  "Storm",
  "Shadow",
  "Dragon",
  "Silver",
  "Iron",
  "Stone",
  "Blood",
  "Black",
  "Raven",
  "Winter",
  "Summer",
  "Autumn",
  "Spring",
  "Oakbane",
  "Ashbane",
  "Elmbane",
  "Birchbane",
  "Rowanbane",
  "Hawthornbane",
  "Willowbane",
  "Maplebane",
  "Pinebane",
  "Cedarbane",
  "Firbane",
  "Sprucebane",
  "Yewbane",
  "Hazelbane",
  "Hollybane",
  "Beechbane",
  "Chestnutbane",
  "Walnutbane",
  "Applebane",
  "Pearbane",
  "Plumbane",
  "Cherrybane",
  "Peachbane",
  "Apricotbane",
  "Grapebane",
  "Melonbane",
  "Berrybane",
  "Orangebane",
  "Lemonbane",
  "Limebane",
  "Mangobane",
  "Banbane",
  "Pineapplebane",
  "Coconutbane",
  "PalmBane",
  "Marrowmarsh",
  "Bonebog",
  "Skullswamp",
  "Fleshfen",
  "Bloodbog",
  "Joy",
  "Hope",
  "Faith",
  "Grace",
  "Charity",
  "Patience",
  "Chastity",
  "Temperance",
  "Prudence",
  "Justice",
  "Fortitude",
  "Pride",
  "Envy",
  "Wrath",
  "Sloth",
  "Greed",
  "Gluttony",
  "Lust",
  "Berg",
  "Burg",
  "Burgess",
  "Bergson",
  "Bergstrom",
  "Bergman",
  "Berglund",
  "Bergquist",
  "Berggren",
  "Roman",
  "Oslo",
  "Trondheim",
  "Bergen",
  "Stavanger",
  "Førde",
  "Nordkapp",
  "Olsen",
  "Hansen",
  "Larsen",
  "Andersen",
  "Pedersen",
  "Nilsen",
  "Kristiansen",
  "Johansen",
  "McDonald",
  "Johnson",
  "Williams",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",
  "Clark",
  "Merryweather",
  "Potts",
  "Hawthorne",
  "Hawthorn",
  "Hawthornberry",
  "Strawberry",
  "Berry",
  "Beryl",
  "Pompellini",
  "Pompelli",
  "Pompellino",
  "Inari",
  "Inarison",
  "Inarsson",
  "Inaridottir",
  "Inayaris",
  "Xifi",
  "Xifison",
  "Xifilius",
  "Xamon",
  "Cerberus",
  "Kerberos",
  "Kerberus",
  "Kerber",
  "Lilith",
  "Cane",
  "Cain",
  "Cainson",
  "Kain",
  "Valentine",
  "Valentino",
  "Levantine",
  "Yang",
  "Yin",
  "Ying",
  "Yong",
  "Jeng",
  "Jong",
  "Jang",
  "Manihl",
  "Loh",
  "Yoh",
  "Yohann",
  "Ioann",
  "Ioki",
  "Oki",
  "Iokison",
  "Okiyama",
  "Nevar",
  "Necar",
  "Carne",
  "Pjotr",
  "Pjotrovich",
  "Pjotrov",
  "Eel",
  "Eal",
  "Eac",
  "Cave",
  "Fsar",
  "Fzar",
  "Underhill",
  "Underwood",
  "Underwater",
  "Underground",
  "Underworld",
  "Underworldly",
  "Underworlder",
  "Underworldian",
  "Subterranean",
  "Subterrestrial",
  "Substratum",
  "Excavator",
  "Digger",
  "Shovel",
  "Spade",
  "Pickaxe",
  "Mattock",
  "Trowel",
  "Hoe",
  "Rake",
  "Fork",
  "Scythe",
  "Sickle",
  "Hammer",
  "Covingtong",
  "Covington",
  "Celeborn",
  "Celebrian",
  "Intov",
  "Intovson",
  "Lek",
  "Hav",
  "Hytte",
  "Hytteberg",
  "Hyttebakk",
  "Hyttebok",
];
